version: "3"

services:
  rabbit1:
    image: rabbitmq:3.8.9-management
    ports:
    - 5672:5672
    - 15672:15672
  rabbit2:
    image: rabbitmq:3.8.9-management
    ports:
    - 5673:5672
    - 15673:15672

